<template>
  <div class="toolBar">
    <span>全部笔记</span>
    <span>同步</span>
    <span>升级</span>
  </div>
</template>

<script type="text/ecmascript-6">
  export default {
    data () {
      return {

      }
    }
  }
</script>

<style lang="scss" rel="stylesheet/scss" scoped>
  .toolBar {
    display: block;
    padding: 5px 10px;
    height: 35px;
    line-height: 35px;
    font-family: "宋体";
    span {
      padding-left: 10px;
      font-size: 13px;
    }
  }
</style>