// 更改添加弹出框状态
export const CHANG_NEWORUPDATECATALOG_DIALOG_STATE = 'CHANG_NEWORUPDATECATALOG_DIALOG_STATE'

export const CHANGE_CURRENTSELECT_CATLOGITEM = 'CHANGE_CURRENTSELECT_CATLOGITEM'

export const CHNAGE_DRAG_TARGET = 'CHNAGE_DRAG_TARGET'

export const SHOW_RECYCLE = 'SHOW_RECYCLE'

export const CHANG_DRAG_STATE = 'CHANG_DRAG_STATE'
